name: Deploy backend into GCLOUD
on:
  push:
    branches: ['main' , 'develop', 'qa']
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: ga-dev
  STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || github.ref == 'refs/heads/qa' && 'qa' || 'dev' }}
  RUN_REGION: europe-west1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  build:
    uses: ./.github/workflows/main.yml@develop
    with:
      environment: ${GITHUB_REF#refs/heads/}
  deploy:
    name: Deploy to ${GITHUB_REF#refs/heads/}
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Auth GCP 
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Setear entorno según la rama
        run: |
          case "${GITHUB_REF#refs/heads/}" in
            "main")
              APP_ID="ga"
              echo "APP_ID=$APP_ID" >> $GITHUB_ENV
              echo "la variable tendrá el valor de $APP_ID"
              ;;
            "qa")
              APP_ID="ga-qa"
              echo "APP_ID=$APP_ID" >> $GITHUB_ENV
              echo "la variable tendrá el valor de $APP_ID"
              ;;
            "develop")
              APP_ID="ga-dev"
              echo "APP_ID=$APP_ID" >> $GITHUB_ENV
              echo "la variable tendrá el valor de $APP_ID"
              ;;
            *)
              echo "no estás en las ramas principales main,qa,develop"
              ;;
          esac

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated --set-env-vars NODE_ENV=${{ secrets.NODE_ENV }},SECRET_JWT=${{secrets.SECRET_JWT}}
