on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test secret"
        default: "Word input"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: From input
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: From secrets
      env:
        DEBUG_PASSWORD: ${{ secrets.PASSWORD_PRIVATE_KEY }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
