on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test secret"
        default: "Word input"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: From input
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: From secrets
      env:
        DEBUG_PASSWORD: ${{ secrets.PASSWORD_PRIVATE_KEY }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python start.py
